name: Tests
on: [push, pull_request]
env:
  CODE_COVERAGE_THRESHOLD_REQUIRED: 33
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install requirements
        run: pip install flake8 pycodestyle pytest pytest-ckan pytest-cov
      - name: Run flake8
        run: flake8 . --count --max-line-length=127 --statistics --exclude ckan

  test:
    needs: lint
    strategy:
      matrix:
        ckan-version: [2.9.5, 2.9, 2.9.7]
        include:
        - ckan-version: 2.9.5
          services-version: 2.9
        - ckan-version: 2.9
          services-version: 2.9
        - ckan-version: 2.9.7
          services-version: 2.9
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: openknowledge/ckan-dev:${{ matrix.ckan-version }}
    services:
      solr:
        image: ckan/ckan-solr-dev:${{ matrix.services-version }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.services-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v3
    - name: Install dependency (common)
      run: |
        # apk add geos-dev
        pip install -r dev-requirements.txt
        pip install -e .
    - name: Setup extension (CKAN >= 2.9)
      run: |
        ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.googleanalyticsbasic --cov-fail-under=${CODE_COVERAGE_THRESHOLD_REQUIRED} --disable-warnings ckanext/googleanalyticsbasic/tests

